name: Deploy to AUR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v3
        with:
          pkgname: bebz-essentials
          pkgbuild: ./PKGBUILD
          assets: |
            bebz.install
            bebzmenu.sh
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_username: ${{ github.actor }}
          commit_email: ${{ github.actor }}@users.noreply.github.com
          commit_message: "Update AUR package"
